// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recyclia.Data;

#nullable disable

namespace Recyclia.Migrations
{
    [DbContext(typeof(DataContextClass))]
    [Migration("20230119183415_foodwastess")]
    partial class foodwastess
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Recyclia.Model.Agency", b =>
                {
                    b.Property<int>("agency_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("agency_id"), 1L, 1);

                    b.Property<string>("agency_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("agency_id");

                    b.ToTable("tbl_Agency");
                });

            modelBuilder.Entity("Recyclia.Model.Agency_Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("agency_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agency_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Login_Agency");
                });

            modelBuilder.Entity("Recyclia.Model.Complaints", b =>
                {
                    b.Property<int>("complaint_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("complaint_id"), 1L, 1);

                    b.Property<string>("complaint_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complaint_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("complaint_topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("customer_mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("complaint_id");

                    b.ToTable("tbl_Complaints");
                });

            modelBuilder.Entity("Recyclia.Model.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_id"), 1L, 1);

                    b.Property<string>("Customer_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customer_id");

                    b.ToTable("tbl_Customer");
                });

            modelBuilder.Entity("Recyclia.Model.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"), 1L, 1);

                    b.Property<string>("agency_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("employee_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("employee_id");

                    b.ToTable("tbl_Employee");
                });

            modelBuilder.Entity("Recyclia.Model.ewaste", b =>
                {
                    b.Property<int>("ewaste_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ewaste_id"), 1L, 1);

                    b.Property<string>("customer_district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ewaste_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ewaste_kilo")
                        .HasColumnType("real");

                    b.Property<float>("ewaste_perkilo_Rs")
                        .HasColumnType("real");

                    b.Property<string>("ewaste_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ewaste_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ewaste_wallet")
                        .HasColumnType("real");

                    b.HasKey("ewaste_id");

                    b.ToTable("tbl_Ewaste");
                });

            modelBuilder.Entity("Recyclia.Model.foodwaste", b =>
                {
                    b.Property<int>("fud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fud_id"), 1L, 1);

                    b.Property<string>("customer_district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("fud_pay")
                        .HasColumnType("real");

                    b.HasKey("fud_id");

                    b.ToTable("tbl_foodwaste");
                });

            modelBuilder.Entity("Recyclia.Model.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_id"), 1L, 1);

                    b.Property<string>("customer_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_interest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_rply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("product_id");

                    b.ToTable("tbl_Product");
                });
#pragma warning restore 612, 618
        }
    }
}
